### ISSUE TITLE
Seek/Rewind buttons

### ISSUE THREAD

**Issue by VishnuSanal** [VishnuSanal/DialogMusicPlayer#24]
It is hard to seek/rewind for small amounts of time (say 10 seconds) whilst playing long audio-books. It is convenient to have buttons to seek & rewind for ten or five seconds.

**Comment by Friptick** [comment]
Yep, this is a super useful feature for spoken-word audio. 10 seconds is the norm for rewind, 10 or 30 for seek.

Looking forward to it.

**Comment by VishnuSanal** [comment]
question:

1. should the seek/rewind time be uniform?
2. if yes, five seconds or ten seconds? or change according to the file size? (say five seconds for _small_ files & ten seconds for longer ones)
3. if not, what should be the seek/rewind times? should this be responsive to the length of the audio file too?

**Comment by Friptick** [comment]
@VishnuSanal thanks for asking!

This is common feature on podcast apps. In my experience, the most common defaults are 10 seconds for rewind and 30 seconds for fast-forward. Because the usual reason to rewind is because you didn't hear or understand something.

I would definitely _not_ recommend making these settings responsive. Just keep it in a setting. It's important to have an idea in advance of how far you'll be jumping back and forward.

**Comment by VishnuSanal** [comment]
@VishnuSanal Okay, so I think we can go with uniform 10s seek/rewind buttons :)

**Comment by VishnuSanal** [comment]
> Seek/rewind buttons looks nice.👌🏿

Thanks!

> > Click & hold for continuous 10sec rewind/forward
> 
> Any plans for this feature?

Um... Please create a new issue, should look into the UX part of this & whether this will be a good addition or not.
