### ISSUE TITLE
Publish DMP app on F-Droid

### ISSUE THREAD

**Issue by shuvashish76** [VishnuSanal/DialogMusicPlayer#3]

**Comment by yephny** [comment]
I agree, this app could be a great addition to F-Droid.

**Comment by VishnuSanal** [comment]
Thanks @shuvashish76 and @yephny for your concerns. It's just that I do not want to publish the app without polishing it. Major components like a Notification etc are missing right now. I should work on them and consider publishing on FDroid & Play Store too.

**Comment by VishnuSanal** [comment]
I started this as a simple project - I feel like v11.0 is publishable. So, WIP for F-Droid :)

**Comment by yephny** [comment]
Great news, rooting for you!

**Comment by shuvashish76** [comment]
A request for packaging has been opened [here](https://gitlab.com/fdroid/rfp/-/issues/1994)

**Comment by IzzySoft** [comment]
And I assume you want your app removed from my repo when it's available at F-Droid? I usually give about 10 days overlap for users to re-orient before I remove. Unless there's an explicit request to keep it in, then it can of course also stay. [See here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) if you want to weight the pros and cons.

**Comment by VishnuSanal** [comment]
> And I assume you want your app removed from my repo when it's available at F-Droid? I usually give about 10 days overlap for users to re-orient before I remove. Unless there's an explicit request to keep it in, then it can of course also stay. [See here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) if you want to weight the pros and cons.

I have no concerns whatsoever in the app staying in IzzyOnDroid too! But if it adds up to your server costs and is a burden for you, then removing makes sense - we do not have any persistent user data or such, that makes the migration easier. But, I feel like uninstalling the app might be a burden for at least some users since we do not have a launcher. The answer to your question would be, @IzzySoft can have the final verdict! :)

**Comment by shuvashish76** [comment]
> I feel like uninstalling the app might be a burden for at least some users since we do not have a launcher.

I don't think so. I assume ppl who knows how to add izzy repo to F-Droid (or using other F-Droid client) know how to uninstall an app from settings. (though not related)

+ Izzy repo is important for us, if we publish DMP on playstore with some paid features in future, as it [helps](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ#footnotes) (2) cross-updates.

**Comment by IzzySoft** [comment]
The app just [passed all tests](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10419#note_814165706), and its metadata is about to be merged. So in a few days (see: [How long does it take for my app to show up on website and client?](https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client)) it will become available at F-Droid – welcome aboard!

As for keeping it in my repo or not: If you say "keep", I happily keep it, @VishnuSanal, it's no "burden" – but I agree with @shuvashish76 here that I see no urgency. Your app has no configuration, no data – so nothing gets lost when uninstalling and re-installing. It's also relatively small (less than 2MB APK size) to be not too much to re-download. If you wish, I could add a note here that the app will soon be available via the "main repo" and then needs an un+re-install to switch over – so new users can decide to wait a few days with their install or are prepared for the switch.

I also second the reasoning that my repo allows for a seamless switch from Play of course, as cross-updates are possible that way (not so with F-Droid's own builds, unless you take the extra care and set up "reproducible builds" (which then are signed with both keys).

So I play back the ball again: it's up to you. If you request to keep it, I'll keep it – otherwise (including you not deciding at all), I'd drop it after a reasonable overlap. That's how the process was designed :smile:

**Comment by VishnuSanal** [comment]
> The app just [passed all tests](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10419#note_814165706), and its metadata is about to be merged. So in a few days (see: [How long does it take for my app to show up on website and client?](https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client)) it will become available at F-Droid – welcome aboard!

@IzzySoft Thanks a lot!!

> So I play back the ball again: it's up to you. If you request to keep it, I'll keep it – otherwise (including you not deciding at all), I'd drop it after a reasonable overlap. That's how the process was designed 😄

I'd let it be removed from IzzyOnDroid :) I feel like it would confuse users if it is there on two repos, with different signatures and updates rolling on both repos at different times. @shuvashish76 Play Store builds doesn't seem like a problem for me as of now. 

> If you wish, I could add a note here that the app will soon be available via the "main repo" and then needs an un+re-install to switch over – so new users can decide to wait a few days with their install or are prepared for the switch.

Please do! Also thanks for letting me serve my apps to the users! You're doing a divine deed by letting devs publish F-Droid incompatible apps (F-Droid underconfident, in my case 🤣) to IzzyonDroid :)

**Comment by IzzySoft** [comment]
Thanks @VishnuSanal – I've put a corresponding note to the metadata here. As those will be archived on removal, re-adding is easy should it be needed one day. And I gladly accept other apps meeting the (slightly laxer) inclusion criteria of my repo, [suggestions are always welcome](https://gitlab.com/IzzyOnDroid/repo/-/issues/) :smiley: My repo served as "stepping stone" to hundreds of apps which then later reached F-Droid when they became "fully compliant" (or "stable enough" :wink:) – while others simply stay (some in both places, e.g. serving betas via mine and stables via F-Droid).

**Comment by shuvashish76** [comment]
DMP now available on [F-Droid](https://f-droid.org/packages/phone.vishnu.dialogmusicplayer)
Thankyou @IzzySoft

**Comment by VishnuSanal** [comment]
> Great news, rooting for you!

@yephny Ping. [It's live](https://f-droid.org/packages/phone.vishnu.dialogmusicplayer), thank you for your support!

**Comment by yephny** [comment]
Downloaded, thanks!
