### ISSUE TITLE
Remember playback speed through entire app

### ISSUE THREAD

**Issue by Gamer750** [VishnuSanal/DialogMusicPlayer#45]
Remember playback speed through entire app

**Comment by VishnuSanal** [comment]
> Remember playback speed through entire app

@Gamer750 hi, thanks for reaching out! I have enabled remembering playback speed for the current session from the next version onwards. remembering playback speed **always** seems like a bad idea to me since DMP can be used for multiple purposes viz. to playmusic, listen to podcasts, just to check the contents of an audio file etc

**Comment by Gamer750** [comment]
> > Remember playback speed through entire app
> 
> @Gamer750 hi, thanks for reaching out! I have enabled remembering playback speed for the current session from the next version onwards. remembering playback speed **always** seems like a bad idea to me since DMP can be used for multiple purposes viz. to playmusic, listen to podcasts, just to check the contents of an audio file etc

Still it would be pretty good

**Comment by Gamer750** [comment]
There are people who only watch video in 2x for them it would be pretty boring to change playback  repeatedly
